sudo: required
services:
  - docker

before_install:
  - docker build -t gayan92tharaka/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gayan92tharaka/react-test npm test -- --coverage

after_success:
  - docker build -t gayan92tharaka/multi-client ./client
  - docker build -t gayan92tharaka/multi-nginx ./nginx
  - docker build -t gayan92tharaka/multi-server ./server
  - docker build -t gayan92tharaka/multi-worker ./worker
#login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#pushing above images to dockerhub
  - docker push gayan92tharaka/multi-client
  - docker push gayan92tharaka/multi-nginx
  - docker push gayan92tharaka/multi-server
  - docker push gayan92tharaka/multi-worker